apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trakzee-ingress
  namespace: trakzee-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: trakzee.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomcat-service
            port:
              number: 80
